### ISSUE TITLE
Sprint 2: Post Management [Parent]

### ISSUE THREAD

**Issue by connor-seneca** [JustinAlaanNguyen/KeebGram#57]
*** This serves as the parent ticket for tickets relating to posts.**

**Description:** 

As a user of KeebGram, I want to be able to create, edit, delete, comment on, and like posts so that I can share my key cap experiences, engage with the community, and keep my content up to date.

**Tasks:**

- [x] #59 Edit Post - Front End
- [x] #58 Delete Post - Front End
- [x] #97 Create Post - Front End
- [x] #67 Like Post/Comment
- [x] #99 Post Likes - Back End
- [x] #100 Post Comments - Back End

**Acceptance Criteria:**

1. Users can create new posts with text and images
2. Users can edit their own posts
3. Users can delete their own posts
4. Users can comment on any post
5. Users can like any post
6. All operations should have appropriate UI feedback (e.g., success/failure messages)

**Testing Scenarios**

1. Creating a post with valid text images
2. Editing a post by changing the text or images
3. Deleting a post and verifying it no longer shows in the users' feed
4. Commenting on a post and verifying the comment appears for other users
5. Liking a post and verifying the like count increases
6. Attempting to edit/delete another users' post/comment should fail

**Comment by vsingh57seneca** [comment]
All tasks implemented
