### ISSUE TITLE
Sprint 2: Product Management [Parent]

### ISSUE THREAD

**Issue by connor-seneca** [JustinAlaanNguyen/KeebGram#60]
***This ticket serves as the parent ticket to Product operations**

**Description:**

As an admin of KeebGram, I want to be able to add, edit, and delete key cap products in the archive/database so that it remains accurate and up to date for the site's users.

**Tasks:**

- [x] #92 Add Product - Back End
- [ ] #91 Add Product - Front End
- [x] #93 Edit Product - Back End
- [ ] #61 Edit Product - Front End
- [x] #94 Delete Product - Back End
- [ ] #62 Delete Product - Front End

**Acceptance Criteria**

1. Admins can add new products with all required details
2. Admins can edit existing products from the database
3. Users can view the list of all products in the archive
4. All operations should have appropriate UI feedback

**Testing Scenarios**

1. Adding a product with valid details
2. Editing a product by changing its name
3. Deleting a product and verify it no longer appears in key cap archive
4. Attempt to add/edit/delete a product from the archive as a regular user (not admin)

**Additional Info/Notes**

- Will require user authentication for admin verification
- Will require admin panel
